### ISSUE TITLE
Formula.sha1 is deprecated

### ISSUE THREAD

**Issue by roblabla** [lokkju/homebrew-formulae#9]
Hello,

None of the formulas here work, as sha1 has been deprecated. Trying to tap this repository yields this : 

```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/lokkju/homebrew-formulae/cdh4-hadoop.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/lokkju/homebrew-formulae/cdh4-hadoop.rb:6:in `<class:Cdh4Hadoop>'
Please report this to the lokkju/formulae tap!
```

for each formulae.

**Comment by lokkju** [comment]
I didn't realize anyone was even using this :D

I'll get it fixed.  thanks.

**Comment by roblabla** [comment]
NP. I just used this to install mpqextractor on my mac (I fixed those formulas myself), as I'm currently fooling around with that ^^.

**Comment by burnbrigther** [comment]
Hi Lokkju - I too am having problems, simply removing xolominer:

Kurts-Mac-Pro:~ kurt$ brew remove xolominer
Error: undefined method `sha1' for #<Class:0x007fc292055d50>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/lokkju/homebrew-formulae/xolominer.rb:8:in `<class:Xolominer>'
/usr/local/Homebrew/Library/Taps/lokkju/homebrew-formulae/xolominer.rb:3:in `load_formula'

Any chance you could provide a method to remove it?  Thanks
